### ISSUE TITLE
rllab version problem

### ISSUE THREAD

**Issue by hcwang95** [openai/vime#8]
It seems that the new rllab is in Python3 but the code for vime is in Python2.

I am wondering if any of you successfully reproduce the results and could you tell me what version of rllab are you using?

Thanks a lot.

**Comment by hcwang95** [comment]
The new version of rllab can be used by only change all xrange() in implementation in Vime to range().

**Comment by BarelySentient** [comment]
Sorry for missing this, I was able to reproduce the results for the Swimmer Gather domain. I switched to python2. The key was to download the py2 branch of rllab rather than the whole rllab github repo.

**Comment by hcwang95** [comment]
Oh, thanks a lot!
